# permissions for end users to view demovolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: demovolume-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hello-k8soperator
    app.kubernetes.io/part-of: hello-k8soperator
    app.kubernetes.io/managed-by: kustomize
  name: demovolume-viewer-role
rules:
- apiGroups:
  - demo.devops.toolbox
  resources:
  - demovolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.devops.toolbox
  resources:
  - demovolumes/status
  verbs:
  - get
